import type { Metadata } from "next";
import { MenuPhotoTab } from "@/components/menu/menu-photo-tab";
import { MenuPageBreads } from "@/utils/menu_bread";
import { MenuPageBurgers } from "@/utils/menu_burger";
import { MenuPageCakes } from "@/utils/menu_cake";
import { MenuPageDonuts } from "@/utils/menu_donut";
import { MenuPagePizzas } from "@/utils/menu_pizza";
import { MenuPageCupCakes } from "@/utils/menu_cup_cake";
import { getNameById, splitIntoThree } from "@/utils";
import { ExtraPizzaTiles } from "@/utils/menu";
import { ArrowLeft, UtensilsCrossed } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Menu Page",
  description: "Generated by create next app",
};
export default async function SingleMenuPage({
  params,
}: {
  params: Promise<{ menuID: string }>;
}) {
  const { menuID } = await params;
  const selectedId = Number(menuID);
  const arrMenus = [
    MenuPagePizzas,
    MenuPageCupCakes,
    MenuPageDonuts,
    MenuPageCakes,
    MenuPageBreads,
    MenuPageBurgers,
  ];
  const paramsArr = arrMenus[selectedId - 1];
  const categoryName = getNameById(selectedId);

  if (!Number.isInteger(selectedId) || !paramsArr || !categoryName) {
    notFound();
  }

  const [first, second, third] = splitIntoThree(paramsArr);

  // split arr into three

  return (
    <main>
      <section className="bg-primary text-white">
        <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
          <Link href="/menu" className="inline-flex items-center gap-2 text-sm font-bold text-secondary-light transition hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">
            <ArrowLeft size={17} aria-hidden="true" /> All menu categories
          </Link>
          <div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold tracking-wide text-secondary-light">
                <UtensilsCrossed size={15} aria-hidden="true" /> {paramsArr.length} ITEMS TO EXPLORE
              </div>
              <h1 className="mt-4 text-3xl font-extrabold tracking-tight sm:text-4xl">{categoryName}</h1>
              <p className="mt-2 text-sm text-white/70 sm:text-base">Pick a favourite, then order it your way.</p>
            </div>
            <p className="text-sm font-medium text-white/60">Scroll to browse categories</p>
          </div>
        </div>
      </section>

      <nav className="border-b border-primary/10 bg-white" aria-label="Menu categories">
        <div className="mx-auto flex max-w-7xl gap-3 overflow-x-auto px-4 py-4 sm:px-6 lg:px-8">
          {ExtraPizzaTiles.map((obj) => (
            <Link
              href={`/menu/${obj.id}`}
              className={`group flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold transition ${selectedId === obj.id ? "bg-primary text-white shadow-sm" : "text-primary/70 hover:bg-secondary-light"}`}
              key={obj.id}
            >
              <span className={`flex size-8 items-center justify-center rounded-lg ${selectedId === obj.id ? "bg-white/15" : "bg-secondary-light"}`}>
                <span className="text-xs">{obj.id}</span>
              </span>
              {obj.name}
            </Link>
          ))}
        </div>
      </nav>

      <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12">
        <MenuPhotoTab
          text={`Featured ${categoryName}`}
          paramsID={selectedId}
          arr={first}
          isPizza={selectedId === 1}
        />
        <MenuPhotoTab
          text={`More ${categoryName} favourites`}
          arr={second}
          paramsID={selectedId}
          isPizza={selectedId === 1}
        />
        <MenuPhotoTab
          paramsID={selectedId}
          text={`Discover more ${categoryName}`}
          arr={third}
          isPizza={selectedId === 1}
        />
      </div>
    </main>
  );
}
