import type { Metadata } from "next";
import { MenuPhotoTab } from "@/components/menu/menu-photo-tab";
import { MenuPageBreads } from "@/utils/menu_bread";
import { MenuPageBurgers } from "@/utils/menu_burger";
import { MenuPageCakes } from "@/utils/menu_cake";
import { MenuPageDonuts } from "@/utils/menu_donut";
import { MenuPagePizzas } from "@/utils/menu_pizza";
import { MenuPageCupCakes } from "@/utils/menu_cup_cake";
import { getNameById, splitIntoThree } from "@/utils";
import { ExtraPizzaTiles } from "@/utils/menu";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Menu Page",
  description: "Generated by create next app",
};
export default async function SingleMenuPage({
  params,
}: {
  params: Promise<{ menuID: string }>;
}) {
  const { menuID } = await params;
  const selectedId = Number(menuID);
  const arrMenus = [
    MenuPagePizzas,
    MenuPageCupCakes,
    MenuPageDonuts,
    MenuPageCakes,
    MenuPageBreads,
    MenuPageBurgers,
  ];
  const paramsArr = arrMenus[selectedId - 1];
  const [first, second, third] = splitIntoThree(paramsArr);

  // split arr into three

  return (
    <>
      <div className=" bg-secondary py-4">
        <p className="text-center font-bold text-xl">Select Menu Item</p>
        <div className="flex justify-around overflow-x-auto snap-x snap-mandatory w-full explore-tiles overflow-y-hidden  py-10 gap-10 scroll-px-10 px-4 bg-secondary ">
          {ExtraPizzaTiles.map((obj, index) => (
            <Link
              href={{ pathname: `/menu/${obj.id}` }}
              className={`flex flex-col ${selectedId === obj.id ? "bg-primary" : ""} items-center justify-between px-2 pt-6 pb-3 rounded-lg`}
              key={index}
            >
              <Image
                src={obj.photoSrc}
                alt={obj.name}
                style={{}}
                className=" w-40 h-40"
              />
              <p
                className={`text-center font-semibold mt-5 ${selectedId === obj.id ? "text-white" : "text-black"} `}
              >
                {obj.name}
              </p>
            </Link>
          ))}
        </div>
      </div>
      <div className="xl:px-48 xl:py-16 md:py-8 md:px-20">
        <MenuPhotoTab
          text={`Premimum ${getNameById(selectedId)}`}
          paramsID={selectedId}
          arr={first}
          isPizza={selectedId === 1}
        />
        <MenuPhotoTab
          text={`Favorite ${getNameById(selectedId)}  `}
          arr={second}
          paramsID={selectedId}
          isPizza={selectedId === 1}
        />
        <MenuPhotoTab
          paramsID={selectedId}
          text={`Classic ${getNameById(selectedId)} `}
          arr={third}
          isPizza={selectedId === 1}
        />
      </div>
    </>
  );
}
