import Image from "next/image";
import { ShieldCheck, Tag } from "lucide-react";
import { CustomizationGroupProps, MenuPageCateProps } from "@/utils/menu";

export function SummaryOrder(customizeOrderArr: CustomizationGroupProps[], product: MenuPageCateProps) {
  const selected = customizeOrderArr.flatMap((group) => group.options.filter((option) => option.quantity > 0).map((option) => ({ ...option, group: group.title })));
  const subtotal = selected.reduce((total, option) => total + option.price * option.quantity, 0);
  const deliveryFee = subtotal * 0.03;
  const serviceFee = subtotal * 0.04;
  const total = subtotal + deliveryFee + serviceFee;
  return <section className="overflow-hidden rounded-2xl border border-primary/10 bg-white shadow-sm"><div className="bg-primary px-5 py-4 text-white"><p className="text-xs font-bold tracking-[0.15em] text-secondary-light">ORDER SUMMARY</p><h2 className="mt-1 text-xl font-extrabold">Review your order</h2></div><div className="p-5"><div className="flex gap-3"><div className="relative size-18 shrink-0 overflow-hidden rounded-xl bg-secondary-light"><Image src={product.photoSrc} alt={product.name} fill sizes="72px" className="object-contain p-1" /></div><div><p className="font-extrabold text-primary">{product.name}</p><p className="mt-1 text-xs leading-4 text-primary/60">Your selected base item</p></div></div><div className="mt-5 divide-y divide-primary/10 border-y border-primary/10">{selected.map((option) => <div className="flex items-start justify-between gap-3 py-3" key={`${option.group}-${option.id}`}><div><p className="text-sm font-bold text-primary">{option.quantity > 1 ? `${option.quantity} × ` : ""}{option.name}</p><p className="mt-0.5 text-xs text-primary/55">{option.group}</p></div><p className="text-sm font-bold text-primary">${(option.price * option.quantity).toFixed(2)}</p></div>)}</div><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between text-primary/65"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div><div className="flex justify-between text-primary/65"><span>Delivery fee</span><span>${deliveryFee.toFixed(2)}</span></div><div className="flex justify-between text-primary/65"><span>Service fee</span><span>${serviceFee.toFixed(2)}</span></div><div className="flex justify-between border-t border-primary/15 pt-3 text-lg font-extrabold text-primary"><span>Total</span><span>${total.toFixed(2)}</span></div></div><div className="mt-5 rounded-xl bg-secondary-light p-3"><div className="flex gap-2"><ShieldCheck size={19} className="shrink-0 text-primary" aria-hidden="true" /><p className="text-xs leading-5 text-primary/75"><strong>Secure checkout.</strong> Your payment details are protected.</p></div></div><button type="button" className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-primary/25 px-4 py-2.5 text-sm font-bold text-primary transition hover:bg-secondary-light"><Tag size={16} aria-hidden="true" /> Add promo code</button></div></section>;
}
