"use client";

import StoreFront from "@/public/stores/pizza_front_re.jpg";
import { Clock3, LocateFixed, MapPin, Motorbike, Package, Phone, Search } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";

const stores = [{ id: 1, name: "Ealing Broadway Store", address: "18 Oakfield Land, Ealing, London W5 2HT", phone: "+44 (0) 207 946 0120", distance: "1.2 km away", deliveryHours: "9:00am – 10:00pm", collectionHours: "9:00am – 11:30pm", image: StoreFront }];

export default function Stores() {
  const [query, setQuery] = useState("");
  const matchingStores = useMemo(() => stores.filter((store) => `${store.name} ${store.address}`.toLowerCase().includes(query.toLowerCase().trim())), [query]);

  return <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12">
    <section className="rounded-3xl bg-primary px-6 py-8 text-white shadow-lg shadow-primary/15 sm:px-10 sm:py-10">
      <p className="text-xs font-bold tracking-[0.16em] text-secondary-light">STORE FINDER</p><h1 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Your next great meal is nearby.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75 sm:text-base">Find a local store for delivery or collection, then order exactly the way you like it.</p>
      <div className="relative mt-6 max-w-2xl"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-primary/55" size={19} aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by town or postcode" aria-label="Search stores by town or postcode" className="w-full rounded-xl bg-white py-3.5 pl-11 pr-32 text-sm text-primary outline-none ring-4 ring-white/10 placeholder:text-primary/45 focus:ring-secondary/60" /><button type="button" onClick={() => setQuery("Ealing")} className="absolute right-2 top-1/2 inline-flex -translate-y-1/2 items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-bold text-primary transition hover:bg-secondary-light"><LocateFixed size={15} aria-hidden="true" /> Near me</button></div>
    </section>
    <section className="pt-8" aria-labelledby="stores-heading"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary/60">Available stores</p><h2 id="stores-heading" className="mt-1 text-2xl font-extrabold text-primary sm:text-3xl">Choose your local store</h2></div><p className="text-sm text-primary/60">{matchingStores.length} {matchingStores.length === 1 ? "store" : "stores"} found</p></div>
      <div className="mt-6 space-y-5">{matchingStores.map((store) => <article className="overflow-hidden rounded-2xl border border-primary/10 bg-white shadow-sm" key={store.id}><div className="grid lg:grid-cols-[18rem_1fr]"><div className="relative min-h-56 bg-secondary-light"><Image src={store.image} alt={`${store.name} storefront`} fill sizes="(max-width: 1024px) 100vw, 288px" className="object-cover" /></div><div className="p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="inline-flex items-center gap-1.5 rounded-full bg-secondary-light px-2.5 py-1 text-xs font-bold text-primary"><MapPin size={14} aria-hidden="true" /> {store.distance}</div><h3 className="mt-3 text-xl font-extrabold text-primary sm:text-2xl">{store.name}</h3><p className="mt-2 max-w-xl text-sm leading-5 text-black/60">{store.address}</p><a href={`tel:${store.phone.replaceAll(" ", "")}`} className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline"><Phone size={15} aria-hidden="true" /> {store.phone}</a></div><span className="w-fit rounded-full bg-green-100 px-3 py-1.5 text-xs font-bold text-green-800">Open now</span></div><div className="mt-6 grid gap-3 border-y border-primary/10 py-4 sm:grid-cols-2"><div className="flex items-center gap-3"><span className="rounded-lg bg-secondary-light p-2 text-primary"><Motorbike size={18} aria-hidden="true" /></span><div><p className="text-xs font-bold uppercase tracking-wide text-primary/55">Delivery</p><p className="mt-0.5 text-sm font-semibold text-primary">{store.deliveryHours}</p></div></div><div className="flex items-center gap-3"><span className="rounded-lg bg-secondary-light p-2 text-primary"><Package size={18} aria-hidden="true" /></span><div><p className="text-xs font-bold uppercase tracking-wide text-primary/55">Collection</p><p className="mt-0.5 text-sm font-semibold text-primary">{store.collectionHours}</p></div></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Link href="/menu" className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white transition hover:bg-primary/90"><Motorbike size={17} aria-hidden="true" /> Order delivery</Link><Link href="/menu" className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-primary/25 px-4 py-3 text-sm font-bold text-primary transition hover:bg-secondary-light"><Package size={17} aria-hidden="true" /> Order collection</Link></div></div></div></article>)}
        {matchingStores.length === 0 && <div className="rounded-2xl border border-dashed border-primary/25 bg-white px-6 py-14 text-center"><Clock3 className="mx-auto text-primary/55" aria-hidden="true" /><p className="mt-3 font-bold text-primary">No nearby stores found</p><button type="button" onClick={() => setQuery("")} className="mt-3 text-sm font-bold text-primary underline">Clear search</button></div>}
      </div></section>
  </main>;
}
