import { Navbar } from "@/components/UI/navbar";
import { Footer } from "@/components/UI/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};
export default function HomeLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Navbar />
      <div className="pt-24 min-h-dvh">{children}</div>
      <Footer />
    </>
  );
}
